// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BaseInput: typeof import('./src/components/base/input.vue')['default']
    CartItem: typeof import('./src/components/cart/item.vue')['default']
    CartList: typeof import('./src/components/cart/list.vue')['default']
    CatalogueListView: typeof import('./src/components/catalogue/list-view.vue')['default']
    CatalogueNftModal: typeof import('./src/components/catalogue/nft-modal.vue')['default']
    CatalogueWalletModal: typeof import('./src/components/catalogue/wallet-modal.vue')['default']
    CatalogueWalletView: typeof import('./src/components/catalogue/wallet-view.vue')['default']
    DappBoard: typeof import('./src/components/dapp/board.vue')['default']
    IntroCarousel: typeof import('./src/components/intro/carousel.vue')['default']
    LegalContents: typeof import('./src/components/legal/contents.vue')['default']
    LegalItem: typeof import('./src/components/legal/item.vue')['default']
    MainConnect: typeof import('./src/components/main/connect.vue')['default']
    MainFooter: typeof import('./src/components/main/footer.vue')['default']
    MainHeader: typeof import('./src/components/main/header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
