// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    InfoCarousel: typeof import('./src/components/info/carousel.vue')['default']
    MainConnect: typeof import('./src/components/main/connect.vue')['default']
    MainHeader: typeof import('./src/components/main/header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
